HTTP_SERVER_HOST=localhost

CORS_ORIGIN=^http:\/\/localhost:[0-9]{1,10}$
CORS_METHODS=*

ONBOARDING_API_KEY=test-api-key

TENDERLY_ACCESS_KEY=test-key
TENDERLY_ACCOUNT_SLUG=test-account
TENDERLY_PROJECT_SLUG=test-project
TENDERLY_API_URL=https://api.tenderly.co

SIMULATION_SUPPORTED_CHAIN_IDS=1,11155111,137,80002
SIMULATION_RATE_LIMIT_MAX=10
SIMULATION_RATE_LIMIT_WINDOW_SECONDS=60
SIMULATION_ALLOWED_ORIGINS=
