# Utilitarian compose file to locally run postgres service
# for integration testing purposes.

version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marketplace
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./test/db/init-schema.sh:/docker-entrypoint-initdb.d/init-schema.sh

volumes:
  postgres_data:
